version: 2.1
jobs:
  build_publish:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout  # checkout source code to working directory
      - run:
          command: |  # create whl and use pipenv to install dependencies
            cd src/python
            python3 -m pip install build wheel
        	python3 -m build --outdir wheelhouse --no-isolation
            python3 -m pip install --upgrade twine && python3 -m twine upload --repository pypi wheelhouse/*

          ## TODO add python test run
          ## pipenv install pytest
          ## pipenv run pytest
workflows:
  build_test_publish:
    jobs:
      - build_publish
